### PR TITLE
lattice diamond formatting

### PR DESCRIPTION
**Pull request by gojimmypi**
diamond uses only single space for delimiters, removes blank lines, and formats lpf files slightly differently.

wondering if it would be best to use manufacturer's format?

### CODE REVIEW

**Comment by gojimmypi** [comment]
note this was created using Lattice Diamond Version (64 bit) 3.10.3.144 for Windows

**Review by gornjas — APPROVED** [review]
Those are excellent change suggestions, thanks for submitting this!

**Comment by gojimmypi** [comment]
@gornjas - thank you.

on the topic of `lpf` files for Windows, note this issue I opened with nextpnr: https://github.com/YosysHQ/nextpnr/issues/235 - specifically regarding Windows format `lpf` files (`CRLF` delimiters) vs unix (`LF` line delimiters) - particularly with a blank last line in the file.

I whipped together a demo showing this here: https://github.com/gojimmypi/nextpnr-issue235

At this time best advice: no blank line at end of file for nextpnr.

**Comment by emard** [comment]
I think it is more prjtrellis than nextpnr issue but
dave reads everything related and he will do what
has to be done :)

**Comment by emard** [comment]
I'm (still) using diamond 3.7 on linux and my diamond
doesn't rewrite or reformat the constraints.

I can also recommend 3.7 instead of newer versions for
building f32c as it allows slightly better fmax.

**Pull request closed without merging**
